<template>
  <video
    :key="video"
    id="v0"
    tabindex="0"
    autobuffer="autobuffer"
    preload="preload"
    autoplay
    loop
    muted
  >
    <source
      type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'
      autoplay
      src="../assets/hos_sc007_sh005_10mbps_H264.mp4"
    />
  </video>
  <section class="section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="content">
            <p>{{ paragraph }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  props: {
    msg: String,
    count: String,
    paragraph: String,
  },
};
</script>

<style>
section {
  z-index: 1;
  position: relative;
}

.content {
  position: sticky;
  position: -webkit-sticky;
  /* top: 33.3%; */
  font-family: Roboto;
  font-size: 35px;
  text-align: left;
  color: white;
  width: 700px;
  padding: 45px;
  margin: 60px;
}

h1 {
  font-size: 3em;
  background: #fff;
  display: inline-block;
  padding: 10px 15px;
  border-radius: 5px;
  margin: 0;
}
.indent-1 {
  float: left;
}
.indent-1 section {
  width: 50%;
  float: left;
}

p {
  font-size: 1.5em;
}

section:nth-of-type(1) {
  height: 1200px;
}
section:nth-of-type(2) {
  height: 1200px;
}
section:nth-of-type(3) {
  height: 1200px;
}
section:nth-of-type(4) {
  height: 1000px;
}
section:nth-of-type(5) {
  height: 4000px;
}

.entered {
  -webkit-animation: text-focus-in 1s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  animation: text-focus-in 1s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

#portal {
  /* background-image: url('/men_sc001_sh005.1001.png'); */
  height: 100vh;
  width: 100vw;
  bottom: 60px;
  right: 60px;
}
#topLeft {
  position: relative;
}
#topLeft img {
  top: 33px;
  left: 42px;
  position: fixed;
  z-index: 2;
}
#topRight {
  position: relative;
}
#topRight img {
  top: 66px;
  right: 46px;
  position: fixed;
  z-index: 2;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-4 16:24:12
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
</style>
